

#         Powered by TabooLib 5.0         #


database:
  use: SQL
  source:
    SQL:
      host: localhost
      port: 3306
      user: root
      password: root
      database: test
      table: chemdah
    MongoDB:
      client: localhost
      database: test
      collection: chemdah

default-stats:
  stay: 100
  style: SOLID
  color: WHITE
  content: '&3[{name}] &7{value}/{target} &f[{percent}%]'

default-track:
  message: 'Tracking [{name}]... click to cancel.'
  mark:
    value: true
    type: HAPPY_VILLAGER
    size: 0
    count: 1000
    distance:
      min: 16
      max: 64
    period: 20
  navigation:
    value: true
    type: END_ROD
    size:
      x: 0
      y: 1.5
    count: 20
    content:
      - '&a[{name}]'
      - '{distance}m'
    distance:
      min: 6
      max: 64
    period: 60
  scoreboard:
    value: true
    content:
      - '&6&lTRACKS'
      - - ''
        - '{name}'
        - '{description}'