#         Powered by TabooLib 6.0         #


database:
  use: LOCAL
  source:
    SQL:
      host: localhost
      port: 3306
      user: root
      password: root
      database: test
      table: chemdah
    MongoDB:
      client: 'mongodb://localhost:3308'
      database: test
      collection: chemdah
  join-select-delay: 20
  user-index: UUID

default-stats:
  stay: 100
  style: SOLID
  color: WHITE
  content: '&3[{name}] &7{value}/{target} &f[{percent}%]'

default-track:
  message: '&7Tracking &3[{name}]&7... Click to cancel.'
  beacon:
    value: true
    type: CLOUD
    size: 0.05
    count: 500
    distance: 32
    period: 2
  landmark:
    value: true
    content:
      - '&a[ - {name} - ]'
      - '({distance}m)'
    distance: 3
  navigation:
    value: true
    sync: true
    type: POINT
    distance: 64
    point:
      type: CRIT
      size:
        x: 0.2
        y: 0.2
      count: 20
      speed: 1
      period: 60
    arrow:
      type: DRIP_LAVA
      y: 0.2
      density: 12
      len: 0.5
      angle: 45
      speed: 1
      period: 150
  scoreboard:
    value: true
    length: 64
    content:
      - '&6&lCHEMDAH TRACKS'
      - - ''
        - ' &f{name}:'
        - ' {description}'
      - ''