

#         Powered by TabooLib 5.0         #


database:
  use: SQL
  source:
    SQL:
      host: localhost
      port: 3306
      user: root
      password: root
      database: test
      table: chemdah
    MongoDB:
      client: localhost
      database: test
      collection: chemdah

default-stats:
  stay: 100
  style: SOLID
  color: WHITE
  content: '&3[{name}] &7{value}/{target} &f[{percent}%]'